apiVersion: v1
kind: Service
metadata:
  name: app-node-service
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http-svc
      port: 3001
  selector:
    app: appnode

