apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http-svc
      port: 27017
  selector:
    app: mongo1




